<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>iTunesLogo.ico</ApplicationIcon>
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="iTunesLogo.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\iTunesControllerLib\iTunesControllerLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Interop.iTunesLib">
      <HintPath>Interop.iTunesLib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>